### PR TITLE
Added footer

### PR DESCRIPTION
**Pull request by FireQueen-3010**
### Description

Added footer for the website

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#7 

## Add relevant screenshot or video (if any)

image

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please accept pr under hacktoberfest

**Review by niloysikdar — APPROVED** [review]
Thanks @FireQueen-3010

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Can you please resolve the conflicts @FireQueen-3010 ?

**Comment by FireQueen-3010** [comment]
Now is it alright? @niloysikdar

**Review by niloysikdar — APPROVED** [review]
Thanks @FireQueen-3010 . Keep contributing.

**Pull request merged**
